### ISSUE TITLE
Failing communication with Teensy v3.1

### ISSUE THREAD

**Issue by bsculley** [cagdasc/Linux-I2C#1]
I have Teensy 3.1 running with the i2c_t3 library (https://github.com/nox771/i2c_t3).  

I am able to communicate with it using the Linux i2c-tools, but not with BBB_I2C with either the standard or Arduino interfaces.

I have Ubuntu 14.04 in the Beaglebone.

**Comment by cagdasc** [comment]
Can you share your code snippet?
